image_width: 1920
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1359.58114,    0.     ,  977.73207,
            0.     , 1362.20844,  584.90093,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.133095, 0.083524, -0.002899, 0.001332, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1294.51171,    0.     ,  981.74825,    0.     ,
            0.     , 1329.60294,  581.76169,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
