image_width: 1920
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1369.45231,    0.     ,  976.35448,
            0.     , 1372.99349,  578.26766,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.137737, 0.075142, -0.004262, 0.000953, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1297.37281,    0.     ,  979.77333,    0.     ,
            0.     , 1338.32901,  573.60697,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
